### ISSUE TITLE
TypeError on init

### ISSUE THREAD

**Issue by WesSec** [techfreaque/octobot-lorentzian-classification#1]
First of all, very very thank you for porting the indicator.

I followed your instructions on a fresh OctoBot instance (windows) but am receiving the following error on start.

`2023-03-24 14:37:46,643 ERROR    TentacleLoader       Error when loading lorentzian_classification: TypeError ('type' object is not subscriptable). If this error persists, try reinstalling your tentacles via "python start.py tentacles --install --all".`

I have tried reinstalling the tentacle.

**Comment by techfreaque** [comment]
Thanks for reporting, I introduce this issue with v 1.1.0 
The latest version is now fixed.
github cache takes a while to update the file referenced in the readme and in the octo ui2 package manager.
But you can directly download/install it from this url:
https://raw.githubusercontent.com/techfreaque/octobot-lorentzian-classification/main/releases/v-1.1.1.1/any_platform.zip

**Comment by techfreaque** [comment]
ooops there were some more issues, use this version:
https://raw.githubusercontent.com/techfreaque/octobot-lorentzian-classification/main/releases/v-1.1.2.1/any_platform.zip

**Comment by techfreaque** [comment]
Closed as it should be fixed
