### ISSUE TITLE
about the get_y_train_series

### ISSUE THREAD

**Issue by HaloRyan** [techfreaque/octobot-lorentzian-classification#5]
Hi Max, 

Thanks for transcribing the code to Python. It is fantastic.

I've checked your code and found your get_y_train_series() method is different than Justin's Pine Version.

Could you explain your reason or thoughts about these changings?

Thanks~

**Comment by techfreaque** [comment]
Hi Ryan,

I'm glad you like it :)

it should be the same, in get_y_train_series there are two ways to get the training data, with the lorentzian I currently only use the bottom one which should be the same (https://github.com/techfreaque/octobot-lorentzian-classification/blob/c5e9de60507b5aa8cdc2b53594bc59730a740bf4/source/tentacles/Meta/Keywords/basic_tentacles/matrix_basic_keywords/ml_utils/classification_functions/classification_utils.py#L257)

The upper one is what I use for my deep neural net evalautor, which works way better, as its not a good indication of a win, if you just check if its above/below after 4 candles

**Comment by HaloRyan** [comment]
Hi Max，

Thankfs for your prompt reply.

I think you've noticed that Justin's version is as follow:
```
src = settings.source
y_train_series = src[4] < src[0] ? direction.short : src[4] > src[0] ? direction.long : direction.neutral
var y_train_array = array.new_int(0)
```

He is using close prices as default compared with other close prices of different time, while your version is comparing the high/low with the close prices. 

```
y_train_series = numpy.where(
            shifted_lows < cutted_closes,
            utils.SignalDirection.short,
            numpy.where(
                shifted_highs > cutted_closes,
                utils.SignalDirection.long,
                utils.SignalDirection.neutral,
            ),
      )
```
I am wondering will the prediction result be a little bit different than Justin's Pine version.

Cheers,

**Comment by techfreaque** [comment]
Ah I see, in the new version you can choose which way you want to use, the tradingview way is the default setting. Its already included in the new Octane version from today and I'll update the standalone version today

**Comment by techfreaque** [comment]
Good catch btw, thanks :)
